name: social_login
description: social_login
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  jwt_decode: ^0.3.1

  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  global_lints:
    path: ../global_lints

