name: core
description: App resources.
version: 1.0.6
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^3.1.0
  json_annotation:
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  device_info_plus: ^12.2.0
  package_info_plus: ^9.0.0
  logger: ^2.6.0
  flutter_cache_manager: ^3.3.0
  network:
    git:
      url: https://github.com/eddawy/flutter_networking
      ref: 1.1.2

  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.4

  flutter_timezone: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  global_lints:
    path: ../global_lints

  build_runner: ^2.7.1
  freezed: 3.2.3
  json_serializable: ^6.11.1

